name: Fetch Weather Data

on:
  schedule:
    - cron: '0 * * * *'  # Exécute toutes les heures
  workflow_dispatch:  # Permet d'exécuter manuellement

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests pandas

    - name: Run script
      run: python script.py
    - name: Commit and Push CSV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data/*.csv
        git commit -m "Add weather data for $(date +'%Y-%m-%d %H:%M')" || exit 0
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

   
    - name: Send error alert to Telegram
      if: failure()
      run: |
        curl -s -X POST "https://api.telegram.org/botYOUR_BOT_TOKEN/sendMessage" \
        -d chat_id=7920070298 \
        -d text="⚠️ Erreur dans GitHub Actions : Le script météo a échoué !"

